### ISSUE TITLE
Can pymodbus sniff electric industries near me?

### ISSUE THREAD

**Issue by Carmzy** [riptideio/pymodbus#1173]
### Versions

* Python: 3.7.5
* OS: Windows 11
* Pymodbus: 2.5.3
* Modbus Hardware (if used): None

### Description

Before everything else, I want to know if it is possible to sniff modbus traffic without any hardware extensions? Like if I want to recieve modbus traffic near me using my bear laptop and of course pymodbus with sockets or what? Is it possible to recieve packets from the electric power plants near me? I really need your answer thanks.

**Comment by rodv92** [comment]
Depends on the medium. (wired or radio)
usually industrial setups are wired and seldom use radio for critical
communications. (and for good reason)

power line communication is probably encrypted, and uses a modulation
scheme over RF spectrum. probably not modbus under the hood also.
plus it's dangerous and probably illegal to sniff it since it comes from
the utility side and it's filtered by meters on the consumer side


back to pymodbus :
For wired communication, for sake of simplicity and to keep it modbus /
pymodbus related there are two options :
Ethernet modbus tcp/udp/tls
RS485 modbus rtu which can be done over a simple twisted pair. basically a
serial protocol.

for ethernet but that would need physical access to an ethernet port with
port mirroring, you would have to sniff modbus traffic with wireshark or
something like that, then process the captured frames to extract the few
bytes that are modbus relevant.
you don't really need pymodbus for that, you could then check what
registers are queried, and find what vendor uses these addresses.

maybe there is even a wireshark plugin for modbus

On a side note, pymodbus is connection oriented, so the traffic has to
enter through a socket, not through a capture.

On the other hand,
RS485 modbus rtu is easier since it is a shared media (just two wires with
all clients and server over it) and I think that with debugging enabled,
pymodbus displays all traffic. whether directed to a server address, a
bridge, or broadcast. keep in mind that modbus addresses are 8 bit. 0 is
broadcast 255 is bridge.

if you really want to get into modbus hacking and you have a modbus device
that you own (for instance, to reverse engineer a proprietary client/server
modbus product suite)
like solar panels controllers setup or whatever) then you have pymodbus
REPL package

**Comment by janiversen** [comment]
Just one small correction to an otherwise good explanation.

You do not need an ethernet port, you can use wifi even if the device is using cabled ethernet, it is a simply question of routing.
