### ISSUE TITLE
Wrong behavior when function code 0x00 is used (and Modbus 1.1 specs)

### ISSUE THREAD

**Issue by bracco23** [riptideio/pymodbus#215]
Hello,

I was trying to test the correct behavior of a Modbus slave when an invalid function code is used. To create a future-proof test, I was trying to use function code 0x00, that is an invalid function code according to the specs (section 4.1 of Modbus Application Protocol 1.1b3).

This is the request class I am using:

```
class WrongFunctionCodeRequest(ModbusRequest):
    function_code = 0x00
    _rtu_frame_size = 4

    def __init__(self, **kwargs):
        ''' Initializes a new instance
        '''
        ModbusRequest.__init__(self, **kwargs)

    def encode(self):
        ''' Encodes the message
        '''
        return b''

    def decode(self, data):
        ''' Decodes data part of the message.

        :param data: The incoming data
        '''
        pass

    def __str__(self):
        ''' Builds a representation of the request

        :returns: The string representation of the request
        '''
        return "WrongFunctionCodeRequest(%d)" % (self.function_code)
```

But when I try to issue this request, things go wrong, it is sent three times and then it says to me it cannot understand the response.

The issue is that if I try to issue a request with function code 0x00, the answer will have function code 0x00 + 0x80 = 0x80, which the code doesn't understand as an error because in ClientDecoder (factory.py:240) the test is done as `>` instead of `>=`

Also, since Modbus Application Protocol 1.1 the terminology is shifted from master-slave to client-server (where the slave has become the server and the master has become the client)

**Comment by dhoomakethu** [comment]
PyModbus as of now supports only valid function codes , since are running your own modified pymodbus stack , you will have to fix it locally as this is not something that will be supported by pymodbus. 
From the specs (please note `normal response`)

> In an exception
response, the server sets the MSB of the function code to 1. This makes the function code
value in an exception response exactly 80 hexadecimal higher than the value would be for a
normal response.
