### ISSUE TITLE
pymodbus.client.sync.ModbusTcpClient read_input_registers get none ?

### ISSUE THREAD

**Issue by fengrujun** [riptideio/pymodbus#38]
HI,sorry for my poor english!
     Why my tcp client get none after perfoming function 'read_input_registers'?My code is:
     from pymodbus.client.sync import ModbusTcpClient as ModbusClient

```
 import logging
 logging.basicConfig()
 log = logging.getLogger()
 log.setLevel(logging.DEBUG)

 client = ModbusClient('192.1.8.146', port=26)
 client.connect()
 arguments = {
 'read_address':    0,
 'read_count':      1,
 'write_address':   1,
 'write_registers': 1,
}
 rq = client.readwrite_registers(**arguments)
 rr = client.read_input_registers(0,16)
 print rr    
 client.close()
```

The result is:
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:0x4d 0x4f 0x44 0x42 0x55 0x53
DEBUG:pymodbus.transaction:getting transaction 1
DEBUG:pymodbus.transaction:Running transaction 2
DEBUG:pymodbus.transaction:0x0 0x2 0x0 0x0 0x0 0x23 0x1 0x4 0x20 0x9a 0xf9 0x79 0xc4 0x9a 0xf9 0x79 0xc4 0x9a 0xf9 0x79 0xc4 0x9a 0xf9 0x79 0xc4 0x9a 0xf9 0x79 0xc4 0x0 0x0 0xc0 0x41 0x9a 0xf9 0x79 0xc4 0x66 0x66 0xbe 0x41
DEBUG:pymodbus.transaction:getting transaction 2
None

```
I use a modbus/tcp  to modbus/rtu gatway as a server,i test it with Modbus Poll,it can get the correct datas,i am sure the device is ok,so i don't know where is going wrong...
```

Thank you!
Billy apple

**Comment by bbinet** [comment]
I get a similar issue: `client.read_input_registers` often return `None`.
Note the I'm using the synchronous tcp client (`pymodbus.client.sync.ModbusTcpClient`)

I tried to investigate a bit, and it seems this is due to the `getTransaction` method which cannot find the transaction id:
https://github.com/bashwork/pymodbus/blob/master/pymodbus/transaction.py#L159-167

Any idea why we experience this issue?

**Comment by bbinet** [comment]
may be the `pymodbus.client.sync.ModbusTcpClient` is not really synchronous?

**Comment by bbinet** [comment]
For the record, I finally managed to fix this issue: it occurred because the socket was not ready when I tried to read_input_registers, and I noticed that if I add `time.sleep(0.001)` after `client.connect()`, it was working.

So I now open the connection with `client.connect()` once, then always keep the same connection when I run `client.read_input_registers`, and everything is fine now, it does not return `None` values anymore.

**Comment by bbinet** [comment]
1 year later, I was hit again by the same issue: `client.read_input_registers` is still returning `None`most of the time despite the `time.sleep(0.001)` trick after the `client.connect()` statement.
This time, to make it work, I had to patch pymodbus code to introduce `time.sleep(0.1)` between `client._send` and `client._recv` in [transaction.py#L64-L68](https://github.com/bashwork/pymodbus/blob/master/pymodbus/transaction.py#L64-L68)

@bashwork: Any idea how we could fix this issue upstream in a clean way?

**Comment by bbinet** [comment]
After more investigation, I've found out that pymodbus would not conform correctly to the modbus specification as it will stop reading data from the tcp socket even if all expected data have not been received.
Actually it does not take into account the `length` field of the MBAP Header as in my case, the first `client._recv` call would not return all data, and pymodbus does not check that expected data length has been read: instead it should read the tcp socket again with `client._recv` until all data is received (according to the `length` field of the MBAP Header).

The following patch fixes this issue for the modbus TCP only. It is more like a workaround patch rather than a well tested patch, but it might be useful to others:

``` diff
diff --git a/pymodbus/transaction.py b/pymodbus/transaction.py
index 70f5b1b..69f86bb 100644
--- a/pymodbus/transaction.py
+++ b/pymodbus/transaction.py
@@ -61,8 +61,10 @@ class ModbusTransactionManager(object):
                 # I need to fix this to read the header and the result size,
                 # as this may not read the full result set, but right now
                 # it should be fine...
-                result = self.client._recv(1024)
-                self.client.framer.processIncomingPacket(result, self.addTransaction)
+                recving = True
+                while recving:
+                    result = self.client._recv(1024)
+                    recving = self.client.framer.processIncomingPacket(result, self.addTransaction)
                 break;
             except socket.error, msg:
                 self.client.close()
@@ -344,7 +346,7 @@ class ModbusSocketFramer(IModbusFramer):
                 self.populateResult(result)
                 self.advanceFrame()
                 callback(result)  # defer or push to a thread?
-            else: break
+            else: return True
 
     def buildPacket(self, message):
         ''' Creates a ready to send modbus packet
```

I can also submit a pull request with this change if you're willing to include it in upstream pymodbus.

**Comment by dhoomakethu** [comment]
Already handled as part of 1.4.0 release

**Comment by l337quez** [comment]
como puedo decodificar para obtener el unit id del cliente
